Feature/like person
kriskuiper/project-tech-team pull request #23
Opened 2019-04-04 08:30 UTC by markschuttehva

What have I done:
- Get a list of users from the database
- Showed the users in html
- Placed the users in a loop
- Every user has his/her own article with a name, image and city

2019-04-04 10:07 UTC, kriskuiper requested changes
See comments

2019-04-04 10:07 UTC, kriskuiper commented on server.js
> +    .post("/matches", matches)
i think the path should be something like "/liked" because your feature is about liking other users and display the liked persons on a seperate page. Also, since we adhere to the standard that you give your function a name that describes it's purpose you should rename it to something like "renderLikedPersons" where it renders a "liked-persons.ejs" file/page where the liked persons get displayed.
```suggestion
    .post("/liked", renderLikedPersons)
```

2019-04-04 10:07 UTC, kriskuiper commented on app/view/matches.ejs
> +    <h1>Who to match?</h1>
Shouldn't this be like "Persons you liked"
```suggestion
    <h1>Persons you liked</h1>
```

2019-04-04 10:07 UTC, kriskuiper commented on app/view/matches.ejs
> +        <!-- Userpage will be the page where all the info is shown -->
Think here should be a for loop for every liked user

2019-04-04 10:07 UTC, kriskuiper commented on app/view/matches.ejs
> +                    <h2>Naam</h2>
This data should be flexible
```suggestion
                    <h2><%= likedPerson.firstName %></h2>
```

2019-04-04 10:07 UTC, kriskuiper commented on server.js
> +const matches = require("./app/controllers/match");
Looks like you `.js` file doesn't match the name you give to your `const`... Again, I would rename it to something like "renderLikedPersons" so it describes it's purpose. Also you want to be consistent in your naming, so don't go naming it match as your filename and matches when importing it somewhere else. I also saw that your function is called "showUsers", it's pretty inconsistent this way, I would name everything the same everywhere. So if you write a module (function) called "showUsers" then also name the `.js` file like "showUsers.js" and import it as `const showUsers = require("./app/controllers/showUsers")`

2019-04-04 10:07 UTC, kriskuiper commented on app/controllers/match.js
> +    for (i = 0; i <= users; i++) {
`let i` should be defined in the for loop
```suggestion
    for (let i = 0; i <= users; i++) {
```

2019-04-04 10:07 UTC, kriskuiper commented on app/controllers/match.js
> +    let i = 0;
So delete it here
```suggestion
```

2019-04-04 10:07 UTC, kriskuiper commented on app/controllers/match.js
> +    const users = 10; //users.length
You can't get the users.length if you've never defined the array of users in the first place. So what you need to do is set a `const users` to match `User.find()` so you get all the users.

2019-04-08 08:33 UTC, kriskuiper requested changes

2019-04-08 08:33 UTC, kriskuiper commented on app/controllers/match.js
> +        for (let i = 0; i < listUser.length; i++) {
Have to loop over the users instead of listUser and check if ID matches the ID in the query:

2019-04-08 08:33 UTC, kriskuiper commented on app/controllers/match.js
> +        for (let i = 0; i < listUser.length; i++) {
Something like this I think:
```suggestion
        for (let i = 0; i < users.length; i++) {
            if (users[i].id === req.query.likedId) {
                console.log("You've already liked this person");
            }
        }
```

2019-04-08 08:33 UTC, kriskuiper commented on app/controllers/match.js
> +        for (let i = 0; i < listUser.length; i++) {
You first have to set the 'likedId' in the query before you can check anything!

2019-04-11 08:46 UTC, Chazzers commented on app/view/users.ejs
> +                        <form action="" method="GET">
Form als partial maken

2019-04-11 08:49 UTC, Chazzers approved these changes

2019-04-11 08:49 UTC, Chazzers commented on app/view/users.ejs
> +                        <form action="" method="GET">
Form als partial maken

2019-04-11 08:49 UTC, Chazzers commented on app/view/users.ejs
> +                <li><a href="/"><img src="/static/media/images/cyclove-logo.svg" alt="Logo CycLove"></a></li>
include nav partial

2019-04-11 08:49 UTC, Chazzers commented on app/view/matches.ejs
> +                        <form action="/matches" method="GET">
Form partial?

2019-04-11 08:49 UTC, Chazzers commented on app/controllers/match.js
> +module.exports = match;
Add newline

2019-04-11 08:51 UTC, kriskuiper approved these changes

2019-04-11 08:51 UTC, kriskuiper commented on app/controllers/totalUsers.js
> +//Require list
I should call this file something like `renderUsers.js` see our [contributing.md](https://github.com/kriskuiper/project-tech-team/blob/development/docs/CONTRIBUTING.md#make-functions-say-what-theyre-intended-to-do)

2019-04-11 08:51 UTC, kriskuiper commented on app/view/matches.ejs
> +                            <p><%= likedpersons[i].city %></p>
Users don't have a city on creating an account, this line is therefore obsolete

2019-04-11 08:51 UTC, kriskuiper commented on app/view/matches.ejs
> +                            <h2><%= likedpersons[i].firstName + " " + likedpersons[i].lastName %></h2>
You should use [es6 template literals](https://developer.mozilla.org/nl/docs/Web/JavaScript/Reference/Template_literals)

2019-04-11 08:52 UTC, merged