Clean/content
kriskuiper/project-tech-team pull request #35
Opened 2019-04-08 13:51 UTC by Chazzers

2019-04-08 13:54 UTC, kriskuiper requested changes

2019-04-08 13:54 UTC, kriskuiper commented on app/static/404.html
> +    href="/media/images/icons/icon-192.png">
Add the closing tag to another line
```suggestion
    href="/media/images/icons/icon-192.png"
    >
```

2019-04-08 13:54 UTC, kriskuiper commented on app/static/404.html
> +    href="/media/images/icons/icon-192.png">
See apple touch icon markup

2019-04-11 17:27 UTC, markschuttehva approved these changes

2019-04-11 17:30 UTC, kriskuiper approved these changes

2019-04-11 17:30 UTC, merged