Making the users and hearts pretty
kriskuiper/project-tech-team pull request #49
Opened 2019-04-11 20:02 UTC by markschuttehva

2019-04-11 22:44 UTC, kriskuiper requested changes

2019-04-11 22:44 UTC, kriskuiper commented on app/static/scripts/main.js
> +// // Register serviceworker
You forgot to comment this back on

2019-04-11 22:44 UTC, kriskuiper commented on app/static/styles/main.css
> +@media screen and (max-width: 120rem) {
Use min-width instead

2019-04-11 22:44 UTC, kriskuiper commented on app/static/styles/main.css
> +  grid-template-columns: repeat(2, 1fr);
Indentation not on point

2019-04-11 22:44 UTC, kriskuiper commented on app/static/styles/main.css
> +  grid-template-columns: repeat(2, 1fr);
On every grid

2019-04-11 22:44 UTC, kriskuiper commented on app/static/styles/main.css
> +main section a article form {
Use BEM principles instead of html selectors

2019-04-11 22:44 UTC, kriskuiper commented on app/static/styles/main.css
> +main section a article form button {
BEM

2019-04-11 22:44 UTC, kriskuiper commented on app/static/styles/main.css
> +main section a article section {
BEM

2019-04-11 22:44 UTC, kriskuiper commented on app/static/sw.js
> +// const CACHE_NAME = "drinkerz-app-cache";
Forgot to comment this out

2019-04-11 22:44 UTC, kriskuiper commented on app/static/sw.js
> +// // Install service worker
Again, comment this on

2019-04-11 22:44 UTC, kriskuiper commented on app/view/users.ejs
> +<meta content="width=device-width, initial-scale=1" name="viewport" />
This already is in `partials/head.ejs`

2019-04-12 08:52 UTC, Aronsmit2 approved these changes

2019-04-12 08:53 UTC, kriskuiper approved these changes

2019-04-12 08:53 UTC, merged